We will use the autograd function in the MXNet framework, thus all data going through the computation graph should be `ndarrays`.
In this notebook you will learn the basics of the NumPy package and MXNet's extensions to it.

To get started, let's import the numpy namespace from MXNet as `np`. For the most parts, you can use it as ordinary `numpy`.

In [3]:
import mxnet as mx
from mxnet import np, npx
import numpy as onp

### Create arrays
Let's see how to create a 2-D array with values from two sets of numbers: 1, 2, 3 and 4, 5, 6.
For the homework we will do everything on a CPU so we don't have to specify the `ctx` argument.

In [4]:
# set ctx=mx.gpu(0) to create one on a GPU
a = np.array(((1,2,3),(5,6,7)), ctx=mx.cpu())
a

array([[1., 2., 3.],
       [5., 6., 7.]])

### Inspect an ndarray's attributes
As with NumPy, the dimensions of each ndarray are accessible by accessing the .shape attribute. We can also query its size, which is equal to the product of the components of the shape. In addition, .dtype tells the data type of the stored values.

In [5]:
(a.shape, a.size, a.dtype, a.context)

((2, 3), 6, dtype('float32'), cpu(0))

### Create a 2-D Array of Ones
We can also create a very simple matrix with the same shape (2 rows by 3 columns), but fill it with 1s.

In [6]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

### Create an Array of Random Values
Often we’ll want to create arrays whose values are sampled randomly. For example, sampling values uniformly between -1 and 1. Here we create the same shape, but with random sampling.

In [7]:
rand_uniform = np.random.uniform(-1,1,size=(3,3))
rand_uniform

array([[ 0.09762704,  0.18568921,  0.43037868],
       [ 0.6885315 ,  0.20552671,  0.71589124],
       [ 0.08976638,  0.6945034 , -0.15269041]])

### Array indexing
Here’s an example of reading a particular element, which returns a 1D array with shape (1,).

In [8]:
a[1,2]

array([7.])

In [9]:
a[:,1:3]

array([[2., 3.],
       [6., 7.]])

In [10]:
a[-1]

array([5., 6., 7.])

In [11]:
a[:,1:3] = 2
a

array([[1., 2., 2.],
       [5., 2., 2.]])

In [12]:
a[1:2,0:2] = 4
a

array([[1., 2., 2.],
       [4., 4., 2.]])

### Converting between MXNet and NumPy
Converting MXNet ndarrays to and from NumPy is easy.

In [13]:
a_np = a.asnumpy()
type(a_np)

numpy.ndarray

We can also convert NumPy arrays to MXNet.


In [14]:
type(npx.from_numpy(a_np))

mxnet.numpy.ndarray

### Check for documentation of a function
Type "?" after a function ot check its documentation.

In [17]:
np.equal?

### Useful functions for the homework

Check if two arrays are equal.

In [18]:
b = np.array([1,2,3])
np.equal(a[0, :], b)

array([ True,  True, False])

In [20]:
b = np.expand_dims(a, 1)
b.shape
b

array([[[1., 2., 2.]],

       [[4., 4., 2.]]])